; default pipemixer config
; refer to pipemixer.ini(5) for options not specified here

[main]
; specified as percentage (1 means 1%)
volume-step=1
volume-min=0
volume-max=150

wraparound=false
display-ids=false

tab-order=playback,recording,output-devices,input-devices,cards
default-tab=playback

[interface]
bar-empty-char=-
bar-full-char=#

[binds]
; keybinds are specified in the form action=key
; supported keys are:
; all printable ASCII/Unicode: a, b, c, 1, 2, 3, а, б, в, etc.
; some special characters: enter/tab/backtab/space/backspace/up/down/right/left
; arbitrary keycodes: code:1234 where 1234 is decimal representation of keycode
; ref: https://invisible-island.net/ncurses/ada/terminal_interface-curses_constants__ads.htm

focus-down=j
focus-down=down
focus-up=k
focus-up=up

focus-first=g
focus-last=G

volume-up=l
volume-up=right
volume-down=h
volume-down=left

tab-next=t
tab-next=tab
tab-prev=T
tab-prev=backtab

tab-1=1
tab-2=2
tab-3=3
tab-4=4
tab-5=5

mute-toggle=m
channel-lock-toggle=space

select-route=p
select-profile=P

set-default=D

confirm-selection=enter
quit-or-cancel-selection=escape
quit=q

